"""
Automated Markdown and HTML Report Generation for BTW (FR-9).
Summarizes QC, Differential Expression, Pathway Enrichment, and Figures into presentation-ready reports.
"""

from __future__ import annotations

import base64
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

import pandas as pd
from btw import logger
from btw.de_analysis.contrasts import DEResult
from btw.enrichment.schema import EnrichmentResult


def generate_markdown_report(
    title: str,
    de_result: DEResult,
    enrichment_result: Optional[EnrichmentResult] = None,
    qc_metrics: Optional[Dict[str, Any]] = None,
    figure_paths: Optional[Dict[str, Union[str, Path]]] = None,
    output_path: Optional[Union[str, Path]] = None,
) -> str:
    """
    Generate a comprehensive Markdown analysis report.

    Parameters
    ----------
    title : str
        Report title.
    de_result : DEResult
        Differential expression analysis result.
    enrichment_result : EnrichmentResult, optional
        Functional enrichment result.
    qc_metrics : dict, optional
        Key QC statistics (e.g. sample counts, library sizes).
    figure_paths : dict, optional
        Mapping of figure captions to file paths.
    output_path : str or Path, optional
        File destination.

    Returns
    -------
    str
        Markdown report content.
    """
    lines = [
        f"# {title}",
        f"**Generated by Bulk Transcriptomics Workbench (`btw`)**  \n",
        "---",
        "## 1. Executive Summary",
    ]

    # DE Summary
    de_df = de_result.results_df
    n_total = len(de_df)
    n_up = len(de_result.up_regulated())
    n_down = len(de_result.down_regulated())
    n_sig = len(de_result.significant_genes())

    lines.extend(
        [
            f"- **Contrast:** `{de_result.contrast[0]}` ({de_result.contrast[1]} vs {de_result.contrast[2]})",
            f"- **Total Genes Analyzed:** {n_total:,}",
            f"- **Differentially Expressed Genes (DEGs):** {n_sig:,} ({n_sig/max(1,n_total)*100:.1f}%)",
            f"  - **Significant UP:** {n_up:,}",
            f"  - **Significant DOWN:** {n_down:,}",
            f"- **Significance Thresholds:** padj <= {de_result.padj_threshold}, |log2FC| >= {de_result.lfc_threshold}",
            "",
        ]
    )

    # QC Summary
    if qc_metrics:
        lines.extend(["## 2. Quality Control Summary"])
        for k, v in qc_metrics.items():
            lines.append(f"- **{k.replace('_', ' ').title()}:** {v}")
        lines.append("")

    # Top DEGs table
    lines.extend(
        [
            "## 3. Top Differentially Expressed Genes",
            "Top significant genes ranked by adjusted p-value:",
            "",
        ]
    )
    sig_df = de_result.significant_genes()
    if not sig_df.empty:
        display_cols = [c for c in ["symbol", "baseMean", "log2FoldChange", "pvalue", "padj", "regulation"] if c in sig_df.columns]
        top_table = sig_df[display_cols].head(10).to_markdown(index=True)
        lines.append(top_table)
    else:
        lines.append("*No genes passed the significance criteria.*")
    lines.append("")

    # Pathway Enrichment
    if enrichment_result is not None:
        lines.extend(
            [
                "## 4. Functional & Pathway Enrichment Analysis",
                f"- **Method:** `{enrichment_result.source_method}`",
                f"- **Gene Set Database:** `{enrichment_result.gene_set_database}`",
                f"- **Total Terms Tested:** {len(enrichment_result.results_df)}",
                f"- **Significant Pathways:** {len(enrichment_result.significant_terms())}",
                "",
            ]
        )
        enr_sig = enrichment_result.significant_terms()
        if not enr_sig.empty:
            cols = [c for c in ["term", "score", "pvalue", "padj", "gene_count"] if c in enr_sig.columns]
            lines.append(enr_sig[cols].head(10).to_markdown(index=False))
        else:
            lines.append("*No pathways passed the significance threshold.*")
        lines.append("")

    # Figures
    if figure_paths:
        lines.extend(["## 5. Publication Visualizations", ""])
        for caption, fpath in figure_paths.items():
            lines.append(f"### {caption}")
            lines.append(f"![{caption}]({Path(fpath).as_posix()})")
            lines.append("")

    md_content = "\n".join(lines)

    if output_path is not None:
        p = Path(output_path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(md_content, encoding="utf-8")
        logger.info(f"Saved Markdown report to: {p}")

    return md_content


def generate_html_report(
    title: str,
    de_result: DEResult,
    enrichment_result: Optional[EnrichmentResult] = None,
    qc_metrics: Optional[Dict[str, Any]] = None,
    figure_paths: Optional[Dict[str, Union[str, Path]]] = None,
    embed_images: bool = True,
    output_path: Optional[Union[str, Path]] = None,
) -> str:
    """
    Generate a self-contained, publication-ready HTML analysis report.

    Parameters
    ----------
    title : str
        Report title.
    de_result : DEResult
        Differential expression analysis result.
    enrichment_result : EnrichmentResult, optional
        Functional enrichment result.
    qc_metrics : dict, optional
        Key QC statistics.
    figure_paths : dict, optional
        Mapping of figure captions to file paths.
    embed_images : bool, default=True
        Whether to embed image files as base64 data URIs.
    output_path : str or Path, optional
        Destination HTML file path.

    Returns
    -------
    str
        HTML report string.
    """
    de_df = de_result.results_df
    n_total = len(de_df)
    n_up = len(de_result.up_regulated())
    n_down = len(de_result.down_regulated())
    n_sig = len(de_result.significant_genes())

    sig_df = de_result.significant_genes()
    display_cols = [c for c in ["symbol", "baseMean", "log2FoldChange", "pvalue", "padj", "regulation"] if c in sig_df.columns]
    top_de_html = sig_df[display_cols].head(10).to_html(classes="styled-table", float_format="%.4g") if not sig_df.empty else "<p>No significant genes detected.</p>"

    enr_html = ""
    if enrichment_result is not None:
        enr_sig = enrichment_result.significant_terms()
        cols = [c for c in ["term", "score", "pvalue", "padj", "gene_count"] if c in enr_sig.columns]
        table_content = enr_sig[cols].head(10).to_html(classes="styled-table", index=False, float_format="%.4g") if not enr_sig.empty else "<p>No significant terms found.</p>"
        enr_html = f"""
        <div class="card">
            <h2>4. Functional & Pathway Enrichment</h2>
            <p><strong>Method:</strong> <code>{enrichment_result.source_method}</code> | <strong>Database:</strong> <code>{enrichment_result.gene_set_database}</code></p>
            {table_content}
        </div>
        """

    fig_html = ""
    if figure_paths:
        fig_items = []
        for caption, fpath in figure_paths.items():
            p = Path(fpath)
            if p.exists() and embed_images and p.suffix.lower() in [".png", ".jpg", ".jpeg", ".svg"]:
                if p.suffix.lower() == ".svg":
                    svg_txt = p.read_text(encoding="utf-8")
                    img_tag = f'<div class="img-container">{svg_txt}</div>'
                else:
                    b64 = base64.b64encode(p.read_bytes()).decode("utf-8")
                    img_tag = f'<div class="img-container"><img src="data:image/png;base64,{b64}" alt="{caption}" /></div>'
            else:
                img_tag = f'<div class="img-container"><img src="{p.as_posix()}" alt="{caption}" /></div>'

            fig_items.append(f"""
            <div class="figure-card">
                <h3>{caption}</h3>
                {img_tag}
            </div>
            """)
        fig_html = f"""
        <div class="card">
            <h2>5. Publication Visualizations</h2>
            <div class="grid-2">
                {''.join(fig_items)}
            </div>
        </div>
        """

    qc_html = ""
    if qc_metrics:
        rows = "".join([f"<li><strong>{k.replace('_', ' ').title()}:</strong> {v}</li>" for k, v in qc_metrics.items()])
        qc_html = f"""
        <div class="card">
            <h2>2. Quality Control Metrics</h2>
            <ul>{rows}</ul>
        </div>
        """

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        :root {{
            --primary: #1F77B4;
            --secondary: #3C5488;
            --up-color: #E64B35;
            --down-color: #4DBBD5;
            --bg: #F8F9FA;
            --card-bg: #FFFFFF;
            --text: #212529;
            --border: #E9ECEF;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background-color: var(--bg);
            color: var(--text);
            margin: 0;
            padding: 30px 20px;
            line-height: 1.6;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
        }}
        header {{
            background: linear-gradient(135deg, #1F77B4, #00A087);
            color: white;
            padding: 30px 40px;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.08);
            margin-bottom: 25px;
        }}
        header h1 {{ margin: 0 0 10px 0; font-size: 28px; }}
        header p {{ margin: 0; opacity: 0.9; }}
        .card {{
            background: var(--card-bg);
            border-radius: 10px;
            padding: 25px 30px;
            margin-bottom: 25px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.04);
            border: 1px solid var(--border);
        }}
        .card h2 {{
            color: var(--secondary);
            margin-top: 0;
            border-bottom: 2px solid var(--border);
            padding-bottom: 8px;
            font-size: 20px;
        }}
        .stats-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }}
        .stat-box {{
            background: #F1F3F5;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
            border-left: 4px solid var(--primary);
        }}
        .stat-box.up {{ border-left-color: var(--up-color); }}
        .stat-box.down {{ border-left-color: var(--down-color); }}
        .stat-box .number {{ font-size: 26px; font-weight: bold; margin-bottom: 4px; }}
        .stat-box .label {{ font-size: 13px; color: #6C757D; text-transform: uppercase; }}
        .styled-table {{
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
            font-size: 14px;
        }}
        .styled-table th, .styled-table td {{
            padding: 10px 14px;
            text-align: left;
            border-bottom: 1px solid var(--border);
        }}
        .styled-table th {{
            background-color: #F8F9FA;
            color: var(--secondary);
            font-weight: 600;
        }}
        .styled-table tr:hover {{ background-color: #F8F9FA; }}
        .grid-2 {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(500px, 1fr));
            gap: 20px;
        }}
        .figure-card {{
            background: #FFFFFF;
            border: 1px solid var(--border);
            border-radius: 8px;
            padding: 15px;
            text-align: center;
        }}
        .figure-card h3 {{ margin-top: 0; font-size: 16px; color: var(--secondary); }}
        .img-container img {{
            max-width: 100%;
            height: auto;
            border-radius: 6px;
        }}
        footer {{
            text-align: center;
            color: #ADB5BD;
            font-size: 13px;
            margin-top: 40px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{title}</h1>
            <p>Downstream Bulk Transcriptomics Workbench (<code>btw</code>) - Automated Executive Report</p>
        </header>

        <div class="card">
            <h2>1. Differential Expression Summary</h2>
            <p><strong>Contrast:</strong> <code>{de_result.contrast[0]}</code> ({de_result.contrast[1]} vs {de_result.contrast[2]}) | 
               <strong>Thresholds:</strong> padj &le; {de_result.padj_threshold}, |log2FC| &ge; {de_result.lfc_threshold}</p>
            <div class="stats-grid">
                <div class="stat-box">
                    <div class="number">{n_total:,}</div>
                    <div class="label">Genes Analyzed</div>
                </div>
                <div class="stat-box">
                    <div class="number">{n_sig:,}</div>
                    <div class="label">Total DEGs</div>
                </div>
                <div class="stat-box up">
                    <div class="number" style="color: var(--up-color);">{n_up:,}</div>
                    <div class="label">Significant UP</div>
                </div>
                <div class="stat-box down">
                    <div class="number" style="color: var(--down-color);">{n_down:,}</div>
                    <div class="label">Significant DOWN</div>
                </div>
            </div>
        </div>

        {qc_html}

        <div class="card">
            <h2>3. Top Differentially Expressed Genes</h2>
            {top_de_html}
        </div>

        {enr_html}

        {fig_html}

        <footer>
            Generated automatically by Bulk Transcriptomics Workbench (<code>btw</code>) &bull; Designed for reproducibility and rigor.
        </footer>
    </div>
</body>
</html>
"""
    if output_path is not None:
        p = Path(output_path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(html_content, encoding="utf-8")
        logger.info(f"Saved HTML report to: {p}")

    return html_content
